import {
  faBookOpen,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faDumbbell,
  faGear,
  faMinus,
  faRepeat,
  faMoon,
  faPen,
  faPlay,
  faPlus,
  faFire,
  faStopwatch,
  faSun,
  faTrash,
  faWeightHanging,
  faWeightScale,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const navIcons = {
  dashboard: faChartLine,
  journal: faDumbbell,
  library: faBookOpen,
  timer: faStopwatch,
  weight: faWeightScale,
}

export const uiIcons = {
  settings: faGear,
  add: faPlus,
  minus: faMinus,
  trash: faTrash,
  sun: faSun,
  moon: faMoon,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  edit: faPen,
  play: faPlay,
  close: faXmark,
  dumbbell: faDumbbell,
  weightHanging: faWeightHanging,
  reps: faRepeat,
  rpe: faFire,
}
